[package]
name = "nmrs"
version = "0.4.0"
edition = "2024"
description = "A Rust library for NetworkManager over D-Bus"
license = "MIT"
repository = "https://github.com/cachebag/nmrs"
documentation = "https://docs.rs/nmrs"
keywords = ["networkmanager", "dbus", "wifi", "linux", "networking"]
categories = ["api-bindings", "asynchronous"]

[dependencies]
zbus = "5.11.0"
zvariant = "5.7.0"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.16"
futures-timer = "3.0.3"
uuid = { version = "1.18.1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "sync", "time"] }