name: Nix Derivation
on:
  pull_request:
    branches: [ master ]  
  push:
    branches: [ master, 2.x-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install fixsha
        run: cargo install fixsha

      - name: Run fixsha
        run: fixsha

      - name: Commit hash fixes
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status -s package.nix) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add package.nix
            git commit -m "chore(nix): fix cargoHash"
            git push
          fi
